# Generated by Django 5.2.7 on 2025-10-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='nationally',
            new_name='nationality',
        ),
    ]
