# Generated by Django 5.2.7 on 2025-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_flights_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('SC', 'Scheduled'), ('DL', 'Delayed'), ('CC', 'Cancelled'), ('CM', 'Completed')], default='SC', max_length=2),
        ),
    ]
